<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="monitorrepository" nsURI="http://palladiosimulator.org/MonitorRepository/1.0"
    nsPrefix="monitorrepository">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="edp2" value="../../../plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint"/>
    <details key="entity" value="../../../plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity"/>
    <details key="identifier" value="../../../plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#/"/>
    <details key="metricspec" value="../../../plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MonitorRepository" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class representing the monitor repository model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" upperBound="-1"
        eType="#//Monitor" containment="true" eOpposite="#//Monitor/monitorRepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A performance measurement for a pcm element (type level)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurementSpecifications"
        lowerBound="1" upperBound="-1" eType="#//MeasurementSpecification" containment="true"
        eOpposite="#//MeasurementSpecification/monitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuringPoint" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/MeasuringPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorRepository" lowerBound="1"
        eType="#//MonitorRepository" eOpposite="#//MonitorRepository/monitors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementSpecification" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A measurement specification for a pcm element including the performance metric and the processing type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metricDescription" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//MetricDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitor" lowerBound="1"
        eType="#//Monitor" eOpposite="#//Monitor/measurementSpecifications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" defaultValueLiteral="" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if self.processingType.oclIsTypeOf(TimeDrivenAggregation) then self.monitor.entityName + ': TimeDrivenAggregation(' + self.processingType.oclAsType(TimeDrivenAggregation).statisticalCharacterization.toString() +')' else self.monitor.entityName + ': ' + self.processingType.toString() endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingType" lowerBound="1"
        eType="#//ProcessingType" containment="true" eOpposite="#//ProcessingType/measurementSpecification">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This attribute specifies in what way measurements shall be further processed or aggregated (besides or before being recorded) upon reception."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggersSelfAdaptations"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatisticalCharacterization" abstract="true">
    <eOperations name="getAggregator" eType="#//util/StatisticalCharacterizationAggregator">
      <eParameters name="expectedDataMetric" eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//NumericalBaseMetricDescription"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticMean" eSuperTypes="#//StatisticalCharacterization">
    <eOperations name="getAggregator" eType="#//util/StatisticalCharacterizationAggregator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.palladiosimulator.experimentanalysis.statisticalcharacterization.aggregators.ArithmeticMeanAggregator(expectedWindowMetric);"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
      <eParameters name="expectedWindowMetric" eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//NumericalBaseMetricDescription"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HarmonicMean" eSuperTypes="#//StatisticalCharacterization">
    <eOperations name="getAggregator" eType="#//util/StatisticalCharacterizationAggregator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.palladiosimulator.experimentanalysis.statisticalcharacterization.aggregators.HarmonicMeanAggregator(expectedWindowMetric);"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
      <eParameters name="expectedWindowMetric" eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//NumericalBaseMetricDescription"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeometricMean" eSuperTypes="#//StatisticalCharacterization">
    <eOperations name="getAggregator" eType="#//util/StatisticalCharacterizationAggregator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.palladiosimulator.experimentanalysis.statisticalcharacterization.aggregators.GeometricMeanAggregator(expectedWindowMetric);"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
      <eParameters name="expectedWindowMetric" eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//NumericalBaseMetricDescription"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Median" eSuperTypes="#//StatisticalCharacterization">
    <eOperations name="getAggregator" eType="#//util/StatisticalCharacterizationAggregator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.palladiosimulator.experimentanalysis.statisticalcharacterization.aggregators.MedianAggregator(expectedWindowMetric);"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
      <eParameters name="expectedWindowMetric" eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//NumericalBaseMetricDescription"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingType" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ProcessingType specifies in what way measurements shall be further processed or aggregated (besides or before being recorded) upon reception."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurementSpecification"
        lowerBound="1" eType="#//MeasurementSpecification" eOpposite="#//MeasurementSpecification/processingType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" abstract="true" eSuperTypes="#//ProcessingType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class of all kinds of ProcessingTypes which define some manner of (statistical) aggregation of consecutive measurements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statisticalCharacterization"
        lowerBound="1" eType="#//StatisticalCharacterization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedSizeAggregation" eSuperTypes="#//Aggregation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="measNum" value="self.numberOfMeasurements > 0"/>
      <details key="frequency" value="self.frequency > 0"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="measNum frequency"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ProcessingType which indicates that fixed-sized sequences of consecutive measurements shall be aggregated."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfMeasurements" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This positive int value determines the number of measurements that shall be aggregated.&#xD;&#xA;By default, this value is set to 10."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This positive int value indicates the frequency of aggregation.&#xD;&#xA;That is, a value of 'n' indicates that the aggreation shall be done each n-th measurement.&#xD;&#xA;By default, this value is set to 1."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeDrivenAggregation" eSuperTypes="#//TimeDriven #//Aggregation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ProcessingType that defines a time-driven (i.e., sliding window based) way of aggregation."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeDriven" eSuperTypes="#//ProcessingType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ProcessingType suitable for measurement specifications that demand a WindowCharacterization (e.g., before being recorded) but are not based on statistical aggregation.&#xD;&#xA;Examples for such measurement specifications are the window-based utilization calculation or the power and energy calculation that bases thereof."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="windowCharacterization"
        lowerBound="1" eType="#//WindowCharacterization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableSizeAggregation" eSuperTypes="#//Aggregation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="retrospection" lowerBound="1"
        eType="#//RetrospectiveCharacterization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedThrough" eSuperTypes="#//ProcessingType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ProcessingType suitable for measurement specifications that specify measurements which shall only be passed to a recorder.&#xD;&#xA;That is, no more processing or aggregation of any kind whatsover is done."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WindowCharacterization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="windowLength" value="self.windowLength > 0.0"/>
      <details key="windowIncrement" value="self.windowIncrement > 0.0"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="windowLength windowIncrement"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Model class to specifiy the characterizing properties of a sliding window."/>
    </eAnnotations>
    <eOperations name="getWindowLengthAsMeasure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=" return Measure .valueOf(getWindowLength(),  javax.measure.unit.SI.SECOND);"/>
        <details key="documentation" value=" Convenience method to retrieve the property 'windowLength' (interpreted as given in seconds) in terms of a javax.measure.Measure"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//ExperimentData/EJSMeasure">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
        <eTypeArguments eClassifier="#//util/Duration"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getWindowIncrementAsMeasure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=" return Measure .valueOf(getWindowIncrement(),  javax.measure.unit.SI.SECOND);"/>
        <details key="documentation" value=" Convenience method to retrieve the property 'windowIncrement' (interpreted as given in seconds) in terms of a javax.measure.Measure"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//ExperimentData/EJSMeasure">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
        <eTypeArguments eClassifier="#//util/Duration"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="10.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The length of the sliding window, in seconds."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowIncrement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="10.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The increment of the sliding window, in seconds."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" defaultValueLiteral="" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="'windowLength ' + self.windowLength.toString() + ' s windowIncrement: ' + self.windowIncrement.toString() + ' s'"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RetrospectiveCharacterization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="retroLength" value="self.retrospectionLength > 0.0"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="retroLength"/>
    </eAnnotations>
    <eOperations name="getRetrospectionLengthAsMeasure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value=" return Measure .valueOf(getRetrospectionLength(),  javax.measure.unit.SI.SECOND);"/>
        <details key="documentation" value=" Convenience method to retrieve the property 'retrospectionLength' (interpreted as given in seconds) in terms of a javax.measure.Measure"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//ExperimentData/EJSMeasure">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
        <eTypeArguments eClassifier="#//util/Duration"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retrospectionLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="10.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This value (interpreted as seconds) determines the length of the retrospection interval.&#xD;&#xA;That is, it specifies which measurements shall be included in the aggregation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" defaultValueLiteral="" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="'retrospectionLength ' + self.windowLength.toString()  + ' s'"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="util" nsURI="http://palladiosimulator.org/MonitorRepository/Util/1.0"
      nsPrefix="monitorrepository">
    <eClassifiers xsi:type="ecore:EDataType" name="Duration" instanceClassName="javax.measure.quantity.Duration"/>
    <eClassifiers xsi:type="ecore:EDataType" name="StatisticalCharacterizationAggregator"
        instanceClassName="org.palladiosimulator.experimentanalysis.statisticalcharacterization.aggregators.StatisticalCharacterizationAggregator"/>
  </eSubpackages>
</ecore:EPackage>
